import { OBJECTIVES } from './config.js';

export function createInitialState() {
  return {
    timeScale: 1,
    paused: false,
    dayTime: 0,
    seasonTime: 0,
    worldTime: 0,
    autosaveTimer: 0,
    enemyWaveTimer: 16,
    workerSpawnDelay: 22,
    workerSpawnTimer: 0,
    weather: 'clear',
    era: 0,
    selected: null,
    selectedBuildType: null,
    placementMode: null,
    dragging: false,
    lastTapTileId: null,
    lastTapAt: 0,
    lastQuickBuildType: 'farm',
    selectedUnits: [],
    buildPreviewTiles: [],
    gameEnded: false,
    resources: {
      gold: 0,
      food: 0,
      wood: 0,
      stone: 0,
      population: 6,
      populationCap: 12,
      workers: 3,
      army: 0,
      prestige: 2,
      stability: 72,
      knowledge: 0,
      threat: 2,
      roads: 0
    },
    techs: new Set(),
    techProgress: null,
    objectives: OBJECTIVES.map(o => ({ ...o, done: false })),
    map: [],
    mapIndex: new Map(),
    buildings: [],
    construction: [],
    units: [],
    projectiles: [],
    enemyCamps: [],
    roads: [],
    territoryRadius: 13.5,
    territoryGrowthAt: 18,
    notifications: [],
    capitalId: null,
    stats: {
      raidsDefeated: 0,
      wonderBuilt: 0,
      armyUnits: 0,
      campsDestroyed: 0
    }
  };
}
